#!/bin/bash

## Update
sudo apt-get update
sudo apt-get install

## Install golang
## Download golang files
cd ~
curl -O https://storage.googleapis.com/golang/go1.10.3.linux-amd64.tar.gz
tar xvf go1.10.3.linux-amd64.tar.gz
sudo chown -R root:root ./go
sudo mv go /usr/local

## Setting go-paths
sudo echo "export GOPATH=$HOME/work" >> ~/.profile
sudo echo "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> ~/.profile
source ~/.profile

mkdir -p $HOME/work/src/github.com/go-squads

## Install PostgresQL
sudo apt-get install postgresql postgresql-contrib

## Install Prometheus


